# Generated by CMake - DO NOT EDIT MANUALLY
# To regenerate: cmake -B build && cmake --build build --target generate-makefile

CXX			:=	c++
CXXFLAGS	:=	-Wall -Wextra -Werror -std=c++98

RM ?= rm -f

NAME	:=	webserv
SOURCES	:=	src/http/Body.cpp \
			src/http/Header.cpp \
			src/http/http_utils.cpp \
			src/http/HttpMethod.cpp \
			src/http/HttpStatus.cpp \
			src/http/Message.cpp \
			src/http/Request.cpp \
			src/http/RequestLine.cpp \
			src/http/Response.cpp \
			src/http/StatusLine.cpp \
			src/http/Uri.cpp \
			src/utils/file_utils.cpp \
			src/utils/Logger.cpp \
			src/utils/utils.cpp \
			src/config/BlockNode.cpp \
			src/config/Config.cpp \
			src/config/DirectiveNode.cpp \
			src/config/Location.cpp \
			src/handlers/IHandler.cpp \
			src/handlers/AutoindexHandler.cpp \
			src/handlers/EchoHandler.cpp \
			src/handlers/FileHandler.cpp \
			src/handlers/RedirectHandler.cpp \
			src/handlers/CgiHandler.cpp \
			src/core/Connection.cpp \
			src/core/Server.cpp \
			src/core/ServerManager.cpp \
			src/core/main.cpp

# Store object and dependency files under build/ to keep the source tree clean
OBJDIR := build/obj
DEPDIR := build/dep

# Default include paths so the generated Makefile can compile sources in-place
# (keeps `#include "Foo.hpp"` working when headers are next to sources)
INCLUDES := -I. -Isrc -Isrc/core -Isrc/http -Isrc/config -Isrc/utils -Isrc/handlers

OBJECTS	:=	$(patsubst %.cpp,$(OBJDIR)/%.o,$(SOURCES))
DEPENDS	:=	$(patsubst %.cpp,$(DEPDIR)/%.d,$(SOURCES))

all: $(STAMP) $(NAME)

$(NAME): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

-include $(DEPENDS)

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(dir $@) $(dir $(DEPDIR)/$*.d)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -MMD -MP -MF $(DEPDIR)/$*.d -c $< -o $@

clean:
	$(RM) $(OBJECTS) $(DEPENDS)
	@rm -rf $(OBJDIR) $(DEPDIR)

fclean: clean
	$(RM) $(NAME) $(STAMP)

re: fclean
	@rm -f $(STAMP)
	$(MAKE) all

test:
	@mkdir -p build
	@cmake -S . -B build
	@cmake --build build --target runTests -- -j
	@ctest --test-dir build --output-on-failure

clean-tests:
	@rm -rf build/Testing

.PHONY: all prepare clean fclean re test clean-tests
